### PR TITLE
Fixes #195: Only allowing typedef iterator_concept in C++20

### LINKED ISSUE #195: vec_iterator member typedef iterator_concept should only be defined in C++20
Hello,

After upgrading Boost to 1.77.0, I had compiler errors when trying to combine `boost::container::flat_map` and `range-v3`.

I'm using apple-clang 13, in C++17 mode.

`vec_iterator` added the following line, with no `#ifdef` around:

```cpp
typedef std::contiguous_iterator_tag                                             iterator_concept;
```

Problem is that `std::contiguous_iterator_tag` is only defined in C++20, and it relies on a forward declaration found in `boost/move/detail/iterator_traits.hpp` (which is illegal IIRC).

Since `range-v3` provides emulated concepts, it has to check the inheritence hierarchy of these tags, which requires them to be defined. As it makes use of `iterator_concept` the compiler is not happy:

```
/Users/theo/.conan/data/range-v3/0.11.0-r3/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/concepts/concepts.hpp:878:13: error: incomplete type >'std::contiguous_iterator_tag' used in type trait expression
          META_IS_BASE_OF(U, T) &&
```

### PR DESCRIPTION
**Pull request by TristanFloch**
Fixes #195.

I was a bit surprised that there were no better way to check if the standard was C++20. Please correct me if there is.

### CODE REVIEW

**Comment by theodelrieu** [comment]
Any news on this?

**Comment by TristanFloch** [comment]
> Any news on this?

None yet.

**Comment by pdimov** [comment]
The relatively new `BOOST_CXX_VERSION` is what one uses nowadays, if no appropriate Config or feature macro exists.

**Comment by pdimov** [comment]
In this case, the feature test macro that controls whether `<iterator>` has the new tags and `iterator_concept` seems to be `__cpp_lib_ranges`. (`<iterator>` must have been included beforehand.)

**Comment by igaztanaga** [comment]
> In this case, the feature test macro that controls whether `<iterator>` has the new tags and `iterator_concept` seems to be `__cpp_lib_ranges`. (`<iterator>` must have been included beforehand.)

In theory, for C++20 features we could also check if <version> header exists and if so, check for __cpp_lib_ranges, I guess.

**Comment by pdimov** [comment]
Checking for header existence is pretty useless in practice, as the header might exist but be empty or generate an `#error`. Fortunately, there's no need for that here, because `<iterator>` always exists.
